# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MESON) += meson-g12a-hg680-fj.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-g12a-x1-prime.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxl-s905x-b860h.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxl-s905x-p212.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-sc2-s905x4-ah212.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-sc2-s905x4-gbit.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-g12a-b860h-v5.dtb

subdir-y       := $(dts-dirs) overlay
