# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-y += rtl8189fs/
obj-y += rtl8822cs/
obj-y += rtl88x2bu/
obj-$(CONFIG_RTL8188EU)		+= rtl8188eu/
obj-$(CONFIG_RTL8180)		+= rtl818x/
obj-$(CONFIG_RTL8187)		+= rtl818x/
obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
obj-$(CONFIG_RTW88)		+= rtw88/
obj-$(CONFIG_RTW89)		+= rtw89/

